#!/bin/bash
# Shared functions for GaiaChess PGO/release build scripts.
# Sourced by build-pgo-windows.sh, build-release.sh, etc.
#
# Prerequisites: llvm-profdata in PATH (or suffixed llvm-profdata-XX)
# Expected variables before sourcing:
#   ROOT_DIR  — repo root (containing Cargo.toml and defaults.conf)
#   NET       — path to NNUE network (optional for PeSTO variants)

# --- x86-64 variant table ---
# Format: "suffix|target-cpu|extra-flags|features"
# Variants ordered from most basic to most specific.
# extra-flags may contain -C target-feature=... to force Rust cfg flags.
#
# NOTE: target-cpu=x86-64-v4 does NOT enable target_feature="avx512f" in rustc.
# You must add -C target-feature=+avx512f,+avx512bw,+avx512vl explicitly.
#
# NOTE: -sse4a on the znver* variants. target-cpu=znver3/4/5 enables SSE4a, and
# LLVM then emits `insertq` — an AMD-only, microcoded and slow instruction that
# buys nothing here (the optimized builds contain none; only the instrumented
# ones did). Intel SDE rejects it, which made the znver4/znver5 variants
# impossible to profile under emulation. Dropping SSE4a costs no performance and
# is what makes those two variants PGO-able in CI.

VARIANTS_PESTO=(
    "x86-64|x86-64||syzygy,nalimov,gaiatb,online-tb"
    "ssse3|x86-64|-C target-feature=+ssse3|syzygy,nalimov,gaiatb,online-tb"
    "sse4-popcnt|x86-64|-C target-feature=+sse4.1,+sse4.2,+popcnt|syzygy,nalimov,gaiatb,online-tb"
)

VARIANTS_NNUE=(
    "avx2|x86-64-v3|-C target-feature=-bmi2|nnue,syzygy,nalimov,gaiatb,online-tb"
    "bmi2|x86-64-v3||nnue,syzygy,nalimov,gaiatb,online-tb"
    "avx512|x86-64-v4|-C target-feature=+avx512f,+avx512bw,+avx512vl|nnue,syzygy,nalimov,gaiatb,online-tb"
    "avx512vnni|x86-64-v4|-C target-feature=+avx512f,+avx512bw,+avx512vl,+avx512vnni|nnue,syzygy,nalimov,gaiatb,online-tb"
    "znver3|znver3|-C target-feature=-sse4a|nnue,syzygy,nalimov,gaiatb,online-tb"
    "znver4|znver4|-C target-feature=+avx512f,+avx512bw,+avx512vl,-sse4a|nnue,syzygy,nalimov,gaiatb,online-tb"
    "znver5|znver5|-C target-feature=+avx512f,+avx512bw,+avx512vl,+avx512vnni,-sse4a|nnue,syzygy,nalimov,gaiatb,online-tb"
)

# All x86-64 variants concatenated
VARIANTS_ALL=("${VARIANTS_PESTO[@]}" "${VARIANTS_NNUE[@]}")

# --- Find llvm-profdata compatible with rustc's LLVM version ---
# The profraw generated by rustc must be read by an llvm-profdata of the same LLVM version.
# Priority: Rust toolchain > suffixed version matching rustc > PATH
find_llvm_profdata() {
    # 1. Look in rustc's sysroot (same LLVM version guaranteed)
    local sysroot
    sysroot="$(rustc --print sysroot 2>/dev/null || true)"
    # Git Bash gets a C:\... sysroot from the native rustc; make it traversable.
    if [ -n "$sysroot" ] && command -v cygpath &>/dev/null; then
        sysroot="$(cygpath -u "$sysroot")"
    fi
    # The host triple's bin/ first: on Windows the toolchain ships
    # llvm-profdata.exe under lib/rustlib/<host-triple>/bin/.
    local host_triple
    host_triple="$(rustc -vV 2>/dev/null | sed -n 's/^host: //p')"
    for t in "$host_triple" x86_64-unknown-linux-gnu; do
        [ -n "$t" ] || continue
        if [ -n "$sysroot" ] && [ -x "$sysroot/lib/rustlib/$t/bin/llvm-profdata$EXE_SUFFIX" ]; then
            echo "$sysroot/lib/rustlib/$t/bin/llvm-profdata$EXE_SUFFIX"
            return
        fi
    done
    # Also check the generic path (macOS, etc.)
    if [ -n "$sysroot" ] && [ -x "$sysroot/bin/llvm-profdata" ]; then
        echo "$sysroot/bin/llvm-profdata"
        return
    fi

    # 2. Look for a suffixed version matching rustc's LLVM version
    local rustc_llvm_ver
    rustc_llvm_ver="$(rustc -vV 2>/dev/null | grep 'LLVM version' | grep -oP '\d+' | head -1 || true)"
    if [ -n "$rustc_llvm_ver" ] && command -v "llvm-profdata-$rustc_llvm_ver" &>/dev/null; then
        echo "llvm-profdata-$rustc_llvm_ver"
        return
    fi

    # 3. Fallback: most recent suffixed version
    local versioned
    versioned=$(compgen -c llvm-profdata- 2>/dev/null | sort -V | tail -1 || true)
    if [ -n "$versioned" ]; then
        echo "$versioned"
        return
    fi

    # 4. Last resort: PATH
    if command -v llvm-profdata &>/dev/null; then
        echo "llvm-profdata"
        return
    fi

    echo "ERROR: llvm-profdata not found." >&2
    return 1
}

# --- Read version from Cargo.toml ---
read_cargo_version() {
    grep '^version' "$ROOT_DIR/Cargo.toml" | head -1 | sed 's/.*"\(.*\)"/\1/'
}

# --- Parse a VARIANTS table entry ---
# Usage: parse_variant "suffix|target-cpu|extra-flags|features"
# Sets: V_SUFFIX, V_CPU, V_EXTRA, V_FEATURES
parse_variant() {
    IFS='|' read -r V_SUFFIX V_CPU V_EXTRA V_FEATURES <<< "$1"
}

# --- Host target triple and output path ---
# Passing --target explicitly is what keeps build scripts and proc-macros
# compiled for the HOST, without the variant's -C target-feature flags.
# Without it, cargo applies the flags to build scripts too: a build script
# compiled for AVX-512 dies with SIGILL on a machine that lacks AVX-512.
# That is exactly what happened on the GitHub runner with zstd-sys during the
# 4.2.0 release — the failure was then swallowed and the previous variant's
# binary got published under the new name.
#
# --- The build is always NATIVE for the host ---
# PGO has to run the instrumented binary, and Rust profiles do not survive a
# change of target triple: the mangled names embed a crate hash derived from
# -C metadata, which includes the triple. Measured on this repo — the same 86
# function paths appear on both sides with different hashes, e.g.
#   gaiachess::see::see  Linux → ..17hb1bdbe350812976fE
#                        Windows → ..17hb7dc437a2036cec3E
# and the overlap is exactly zero. Collecting profiles on Linux and feeding them
# to a Windows cross-compile is therefore a silent no-op — which is what the
# Windows binaries shipped with until now. Each platform must profile itself, so
# the Windows release is built on a Windows runner.
#
# --- Why MSVC and not mingw on Windows ---
# -Cprofile-generate needs the profiler_builtins crate, which ships inside the
# target's rust-std. The x86_64-pc-windows-gnu std does NOT contain it:
#   error[E0463]: can't find crate for `profiler_builtins`
#   note: the compiler may have been built without the profiler runtime
# so the gnu target cannot be PGO-built at all, on any host. MSVC can, which is
# also what tools/pgo/build-pgo-windows.bat has always used.
# +crt-static is added below so the .exe stays self-contained, with no VC++
# redistributable for users to install — the property mingw gave us for free.
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        HOST_TARGET="${HOST_TARGET:-x86_64-pc-windows-msvc}"
        EXE_SUFFIX=".exe" ;;
    *)
        HOST_TARGET="${HOST_TARGET:-x86_64-unknown-linux-gnu}"
        EXE_SUFFIX="" ;;
esac
NATIVE_BIN="target/$HOST_TARGET/release/gaiachess$EXE_SUFFIX"

# Flags added to every variant on this host (empty on Linux).
HOST_EXTRA_FLAGS=()
case "$HOST_TARGET" in
    *windows-msvc) HOST_EXTRA_FLAGS=("-C" "target-feature=+crt-static") ;;
esac

# CARGO_TARGET_<TRIPLE>_RUSTFLAGS, with the triple upper-cased and - turned to _
RUSTFLAGS_VAR="CARGO_TARGET_$(echo "$HOST_TARGET" | tr 'a-z-' 'A-Z_')_RUSTFLAGS"

# --- Hand rustc/llvm-profdata a path they understand ---
# Under Git Bash the tools are native Windows programs and do not read
# /c/... paths; cygpath converts. A no-op everywhere else.
native_path() {
    if command -v cygpath &>/dev/null; then cygpath -w "$1"; else echo "$1"; fi
}

# --- Flags are passed via CARGO_TARGET_<TRIPLE>_RUSTFLAGS ---
# Two traps, both of which silently broke the 4.2.0 release:
#
#  1. That variable takes SPACE-separated flags. The \x1f encoding belongs to
#     CARGO_ENCODED_RUSTFLAGS only; feeding \x1f here yields
#     "unknown codegen option: `␟target-cpu`".
#  2. RUSTFLAGS must be UNSET, not set to "". Cargo picks the first source that
#     is set, and an empty-but-defined RUSTFLAGS shadows the target-specific
#     variable — the flags are then silently dropped and every variant compiles
#     identically. Hence `env -u RUSTFLAGS -u CARGO_ENCODED_RUSTFLAGS`.
#
# Flags are joined with "${array[*]}" (space, the default IFS) at each call site.

# --- Collecting profiles for an ISA the build machine cannot execute ---
#
# PGO needs to RUN the instrumented binary. A machine without AVX-512 cannot run
# an AVX-512 variant: it dies with SIGILL. GitHub-hosted runners cannot be relied
# on here, and the problem is worse than "no AVX-512" — it is a per-job lottery:
# the pool mixes EPYC 7763 (Zen 3, no AVX-512), Xeon 8370C/8272CL (AVX-512
# present) and EPYC 9V74 (Zen 4 whose AVX-512 Azure masks out of CPUID on part of
# the fleet). GitHub's own answer on actions/runner-images#3389 is that hosted
# agents are "not guaranteed to have AVX-512" and that self-hosting is the only
# way to get it. Probing /proc/cpuinfo therefore answers differently from one
# release to the next, which is how the AVX-512 binaries ended up shipping with
# or without PGO at random.
#
# The fix (standard practice for AVX-512 CI): don't hunt for capable hardware,
# emulate with Intel SDE.
# QEMU is not an option — qemu-user masks every avx512 bit under TCG and the
# binary SIGILLs.
#
# PGO_SDE selects the policy:
#   require — SDE is mandatory for variants that need it; hard failure when it is
#             missing. This is what CI uses: the property that matters is that we
#             can never again silently publish a non-PGO AVX-512 binary.
#   auto    — SDE when available, else native when the host can manage, else fall
#             back to a non-PGO build (default; keeps local builds usable).
#   never   — never emulate (the previous behaviour).
PGO_SDE="${PGO_SDE:-auto}"

# Search depth for the profiling bench run. Empty = the binary's own default.
# Emulation is only ~8x slower than native (measured on Zen 5 with SDE 10.8),
# so the emulated run can afford a deep search: depth 13 costs ~22 s of emulated
# bench and yields a profile indistinguishable in quality from a native depth-16
# one (znver5: 716.0K NPS vs 723.8K, overlapping 95% CIs).
PGO_BENCH_DEPTH="${PGO_BENCH_DEPTH:-}"
PGO_SDE_BENCH_DEPTH="${PGO_SDE_BENCH_DEPTH:-13}"

# --- Locate Intel SDE ---
# Honours SDE_PATH (a directory or the executable itself), then PATH.
# On Windows the binary is sde.exe/sde64.exe, and setup-sde exports SDE_PATH as
# a C:\... path that bash cannot stat — hence the cygpath conversion.
find_sde() {
    local cand root
    root="${SDE_PATH:-}"
    if [ -n "$root" ] && command -v cygpath &>/dev/null; then
        root="$(cygpath -u "$root")"
    fi
    if [ -n "$root" ]; then
        for cand in "$root" \
                    "$root/sde64$EXE_SUFFIX" "$root/sde$EXE_SUFFIX" \
                    "$root/sde64" "$root/sde"; do
            if [ -f "$cand" ] && [ -x "$cand" ]; then
                echo "$cand"
                return 0
            fi
        done
    fi
    for cand in sde64 sde; do
        if command -v "$cand" &>/dev/null; then
            command -v "$cand"
            return 0
        fi
    done
    return 1
}

# --- Does this variant need emulation on an arbitrary build machine? ---
# True for anything beyond x86-64-v3, i.e. the AVX-512 variants. znver3 is NOT
# in this set: it usually runs fine, and the SIGILL retry below covers it when it
# does not. Returns 0 when emulation is required.
variant_needs_emulation() {
    case "$V_EXTRA" in
        *+avx512*) return 0 ;;
    esac
    case "$V_CPU" in
        znver4|znver5) return 0 ;;   # belt and braces: both carry +avx512 above
    esac
    return 1
}

# --- Build the bench argv for a given depth ("" = the binary's default) ---
# Sets BENCH_ARGV.
bench_argv() {
    BENCH_ARGV=(bench)
    if [ -n "$1" ]; then
        BENCH_ARGV+=(--depth "$1")
    fi
}

# --- Run the instrumented binary to collect profiles ---
# Usage: collect_profiles BINARY PGO_DIR
# Exit codes, which the caller must distinguish:
#   0 — profiles collected
#   1 — cannot profile here; caller should fall back to a non-PGO build
#   2 — hard error; caller should fail the build
collect_profiles() {
    local bin="$1" pgo_dir="$2"
    local sde rc=0
    sde="$(find_sde || true)"

    # --- Variants that must be emulated: always SDE, so that the binary we ship
    # --- is identical whatever CPU the runner happened to draw.
    if variant_needs_emulation; then
        if [ "$PGO_SDE" = "never" ]; then
            echo "  PGO_SDE=never — not profiling '$V_SUFFIX'" >&2
            return 1
        fi
        if [ -z "$sde" ]; then
            echo "  Intel SDE not found: '$V_SUFFIX' cannot be profiled on this machine." >&2
            echo "  Install SDE, or point SDE_PATH at its directory." >&2
            degrade_or_fail; return
        fi
        bench_argv "$PGO_SDE_BENCH_DEPTH"
        echo "  emulating with Intel SDE: $sde -future -- $bin ${BENCH_ARGV[*]}"
        # -future rather than a per-variant -arch: it enables every known ISA
        # extension, covering both +avx512vnni and everything else that
        # -C target-cpu=znver4/znver5 lets LLVM emit (vbmi, vbmi2, bitalg,
        # vpopcntdq, bf16, gfni, vaes...).
        "$sde" -future -- "$bin" "${BENCH_ARGV[@]}" || rc=$?
        if [ "$rc" -ne 0 ]; then
            echo "  bench under SDE failed for '$V_SUFFIX' (exit $rc)" >&2
            degrade_or_fail; return
        fi
        return 0
    fi

    # --- Variants that should run natively.
    bench_argv "$PGO_BENCH_DEPTH"
    "$bin" "${BENCH_ARGV[@]}" || rc=$?
    if [ "$rc" -eq 0 ]; then
        return 0
    fi

    # 132 = 128 + SIGILL(4). The host turned out not to support this variant
    # after all — the znver3-on-Cascade-Lake case, or an AVX-512 host without the
    # VNNI the variant wants. Retry under emulation before giving up on PGO.
    if [ "$rc" -ne 132 ]; then
        echo "ERROR: instrumented bench failed for '$V_SUFFIX' (exit $rc)" >&2
        return 2
    fi
    echo "  bench died with SIGILL: this host cannot execute '$V_SUFFIX' natively"

    if [ "$PGO_SDE" = "never" ] || [ -z "$sde" ]; then
        echo "  no emulation available to profile '$V_SUFFIX'" >&2
        degrade_or_fail; return
    fi

    # A partial run may have left profiles behind; start from a clean slate.
    rm -f "$pgo_dir"/*.profraw
    bench_argv "$PGO_SDE_BENCH_DEPTH"
    echo "  retrying under Intel SDE: $sde -future -- $bin ${BENCH_ARGV[*]}"
    rc=0
    "$sde" -future -- "$bin" "${BENCH_ARGV[@]}" || rc=$?
    if [ "$rc" -ne 0 ]; then
        echo "  bench under SDE also failed for '$V_SUFFIX' (exit $rc)" >&2
        degrade_or_fail; return
    fi
}

# --- What to do when a variant cannot be profiled ---
# Under PGO_SDE=require, nothing may ship without PGO: fail the build (2).
# Otherwise degrade to a non-PGO build (1). Keeping this in one place is what
# guarantees the CI cannot quietly publish an unprofiled binary again.
degrade_or_fail() {
    if [ "$PGO_SDE" = "require" ]; then
        echo "ERROR: PGO_SDE=require — refusing to ship '$V_SUFFIX' without PGO" >&2
        return 2
    fi
    echo "  falling back to a non-PGO build for '$V_SUFFIX'" >&2
    return 1
}

# --- Merge the collected profiles, and refuse to merge nothing ---
# Usage: merge_profiles PGO_DIR
# An empty profile silently produces an unoptimised binary, so it must be loud.
merge_profiles() {
    local pgo_dir="$1"
    local profraw_count prof_funcs

    profraw_count=$(find "$pgo_dir" -name '*.profraw' | wc -l)
    if [ "$profraw_count" -eq 0 ]; then
        echo "ERROR: no .profraw produced for '$V_SUFFIX' — the bench wrote no profile" >&2
        return 1
    fi

    if ! "$LLVM_PROFDATA" merge -o "$(native_path "$pgo_dir/merged.profdata")" \
            "$(native_path "$pgo_dir")"; then
        echo "ERROR: llvm-profdata merge failed for '$V_SUFFIX'" >&2
        return 1
    fi
    echo "  $profraw_count profraw files merged"

    prof_funcs=$("$LLVM_PROFDATA" show "$(native_path "$pgo_dir/merged.profdata")" 2>/dev/null \
        | grep -i 'Total functions' | grep -oE '[0-9]+' | head -1 || true)
    echo "  profiled functions: ${prof_funcs:-unknown}"
    if [ -n "$prof_funcs" ] && [ "$prof_funcs" -eq 0 ]; then
        echo "ERROR: merged profile for '$V_SUFFIX' contains no function" >&2
        return 1
    fi
}

# --- Optimized build without PGO ---
# Fallback when profiles cannot be collected on this machine. The binary is
# still built with the variant's target-cpu/target-feature — it just misses
# the profile-guided layout.
build_nopgo_native() {
    local flags=("$@")
    rm -f "$NATIVE_BIN"
    if ! env -u RUSTFLAGS -u CARGO_ENCODED_RUSTFLAGS "${env_vars[@]}" \
        "$RUSTFLAGS_VAR"="${flags[*]}" \
        cargo build --release --target "$HOST_TARGET" \
            --features "$V_FEATURES" "${extra_cargo_args[@]}" 2>&1
    then
        echo "ERROR: non-PGO build failed for '$V_SUFFIX'" >&2
        return 1
    fi
    if [ ! -x "$NATIVE_BIN" ]; then
        echo "ERROR: $NATIVE_BIN missing after non-PGO build of '$V_SUFFIX'" >&2
        return 1
    fi
    echo "  => $NATIVE_BIN (no PGO)"
    ls -lh "$NATIVE_BIN"
    echo
}

# --- PGO build for a variant (native Linux) ---
# Arguments: VARIANT_ENTRY PGO_DIR [EXTRA_CARGO_ARGS...]
# Produces: $NATIVE_BIN (Linux) or target/TARGET/release/gaiachess.exe (cross)
build_pgo_native() {
    local variant="$1" pgo_dir="$2"
    shift 2
    local extra_cargo_args=("$@")

    parse_variant "$variant"
    local env_vars=()

    # MODEL= only for NNUE variants
    if [[ "$V_FEATURES" == *nnue* ]]; then
        if [ -z "${NET:-}" ]; then
            echo "ERROR: NET not set for NNUE variant '$V_SUFFIX'" >&2
            return 1
        fi
        env_vars+=("MODEL=$NET")
    fi

    echo "=========================================="
    echo "=== Building $V_SUFFIX (cpu=$V_CPU, features: $V_FEATURES) ==="
    echo "=========================================="
    echo

    # Build rustc flags (space-joined into CARGO_TARGET_<TRIPLE>_RUSTFLAGS)
    local base_flags=("-C" "target-cpu=$V_CPU" ${HOST_EXTRA_FLAGS[@]+"${HOST_EXTRA_FLAGS[@]}"})
    if [ -n "$V_EXTRA" ]; then
        # V_EXTRA is like "-C target-feature=+avx512f,..."
        # shellcheck disable=SC2206
        base_flags+=($V_EXTRA)
    fi

    # Never let a previous variant's binary survive into this one: if a build
    # fails, we must notice it instead of publishing a stale duplicate.
    rm -f "$NATIVE_BIN"

    # Step 1: Instrumented build
    echo "--- Step 1/4: Instrumented build ($V_CPU) ---"
    rm -rf "$pgo_dir"
    local instr_flags=("${base_flags[@]}" "-Cprofile-generate=$(native_path "$pgo_dir")")
    if ! env -u RUSTFLAGS -u CARGO_ENCODED_RUSTFLAGS "${env_vars[@]}" \
        "$RUSTFLAGS_VAR"="${instr_flags[*]}" \
        cargo build --release --target "$HOST_TARGET" \
            --features "$V_FEATURES" "${extra_cargo_args[@]}" 2>&1
    then
        echo "ERROR: instrumented build failed for '$V_SUFFIX'" >&2
        return 1
    fi
    if [ ! -x "$NATIVE_BIN" ]; then
        echo "ERROR: $NATIVE_BIN missing after instrumented build of '$V_SUFFIX'" >&2
        return 1
    fi

    # Step 2: Collect profiles (natively, or under Intel SDE)
    echo "--- Step 2/4: Collecting profiles (bench) ---"
    local collect_rc=0
    collect_profiles "./$NATIVE_BIN" "$pgo_dir" || collect_rc=$?
    case "$collect_rc" in
        0) ;;
        1)  # Cannot profile here: still build the variant, just without PGO.
            echo "--- PGO skipped for $V_SUFFIX: profiles could not be collected ---"
            build_nopgo_native "${base_flags[@]}" || return 1
            return 0 ;;
        *)  return 1 ;;
    esac
    echo

    # Step 3: Merge profiles
    echo "--- Step 3/4: Merging profiles ---"
    merge_profiles "$pgo_dir" || return 1

    # Step 4: Optimized rebuild
    echo "--- Step 4/4: PGO + LTO build ($V_CPU) ---"
    rm -f "$NATIVE_BIN"
    local pgo_flags=("${base_flags[@]}" "-Cprofile-use=$(native_path "$pgo_dir/merged.profdata")")
    if ! env -u RUSTFLAGS -u CARGO_ENCODED_RUSTFLAGS "${env_vars[@]}" \
        "$RUSTFLAGS_VAR"="${pgo_flags[*]}" \
        cargo build --release --target "$HOST_TARGET" \
            --features "$V_FEATURES" "${extra_cargo_args[@]}" 2>&1
    then
        echo "ERROR: PGO build failed for '$V_SUFFIX'" >&2
        return 1
    fi
    if [ ! -x "$NATIVE_BIN" ]; then
        echo "ERROR: $NATIVE_BIN missing after PGO build of '$V_SUFFIX'" >&2
        return 1
    fi

    echo "  => $NATIVE_BIN"
    ls -lh "$NATIVE_BIN"
    echo
}

# --- Cross-compiled Windows build (NO PGO) ---
# Kept for local convenience only. There is deliberately no PGO here: profiles
# collected on Linux do not match a Windows binary's symbols (the mangled names
# embed a crate hash derived from -C metadata, which includes the target
# triple), so -Cprofile-use would be a silent no-op. The release Windows
# binaries are built and profiled natively on a Windows runner instead.
# Arguments: VARIANT_ENTRY WIN_TARGET
build_nopgo_windows_cross() {
    local variant="$1" win_target="$2"

    parse_variant "$variant"
    local env_vars=()
    local cargo_exe="target/$win_target/release/gaiachess.exe"

    if [[ "$V_FEATURES" == *nnue* ]]; then
        if [ -z "${NET:-}" ]; then
            echo "ERROR: NET not set for NNUE variant '$V_SUFFIX'" >&2
            return 1
        fi
        env_vars+=("MODEL=$NET")
    fi

    echo "=========================================="
    echo "=== Building $V_SUFFIX (cpu=$V_CPU, target=$win_target, no PGO) ==="
    echo "=========================================="
    echo

    rm -f "$cargo_exe"
    local base_flags=("-C" "target-cpu=$V_CPU")
    if [ -n "$V_EXTRA" ]; then
        # shellcheck disable=SC2206
        base_flags+=($V_EXTRA)
    fi

    if ! env -u RUSTFLAGS -u CARGO_ENCODED_RUSTFLAGS "${env_vars[@]}" \
        CARGO_TARGET_X86_64_PC_WINDOWS_GNU_RUSTFLAGS="${base_flags[*]}" \
        cargo build --release --target "$win_target" --features "$V_FEATURES" 2>&1
    then
        echo "ERROR: Windows cross build failed for '$V_SUFFIX'" >&2
        return 1
    fi
    if [ ! -f "$cargo_exe" ]; then
        echo "ERROR: $cargo_exe missing after Windows build of '$V_SUFFIX'" >&2
        return 1
    fi

    echo "  => $cargo_exe (no PGO)"
    ls -lh "$cargo_exe"
    echo
}
